#use "topfind";;
#thread;;
#require "extlib";;
#load "ArborescenceCowebo_t.cmo";;
open ArborescenceCowebo_t;;
print_endline "Fin Chargement modules Clementine";;



let arbo = [{author = ""; createPermission = true; created = "Wed Jan 25 2012 11:25:03 GMT+0100 (CET)";
             creator = "admin"; droits = ""; id = "0e99a9c2-033d-4511-bcf4-c4874a786fa9";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/octet-stream";
    modified = "Wed Jan 25 2012 11:25:03 GMT+0100 (CET)"; modifier = "admin";
    miniature = ""; nodeType = "document"; parentId = "3e4e9b05-f9f2-4443-823f-3fb9bf3e39a3";
    pathAlf = ""; size = 0; nomfichier = "0e99a9c2-033d-4511-bcf4-c4874a786fa9";
    version = "0"; versionable = true; messages_recus = []; messages_envoyes = [];
    infosDossier = []; cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Jan 25 2012 12:00:03 GMT+0100 (CET)";
    creator = "admin"; droits = ""; id = "7a976ec8-51b9-4cab-baff-85bced879f7f";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/octet-stream";
    modified = "Wed Jan 25 2012 12:00:03 GMT+0100 (CET)"; modifier = "admin";
    miniature = ""; nodeType = "document"; parentId = "8108e738-4f30-42e8-a9b5-32ab28afb185";
    pathAlf = ""; size = 0; nomfichier = "7a976ec8-51b9-4cab-baff-85bced879f7f";
    version = "0"; versionable = true; messages_recus = []; messages_envoyes = [];
    infosDossier = []; cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Tue Nov 08 2011 10:28:07 GMT+0100 (CET)";
    creator = "System"; droits = ""; id = "3e4e9b05-f9f2-4443-823f-3fb9bf3e39a3";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Jan 25 2012 11:25:03 GMT+0100 (CET)"; modifier = "admin";
    miniature = ""; nodeType = "folder"; parentId = "2cea9090-7329-4f65-b4f9-1012de70d6ac";
    pathAlf = ""; size = 0; nomfichier = "Espace racine"; version = "";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = "L'espace racine de la societe"};
    children = []};
   {author = ""; createPermission = true; created = "Tue Nov 08 2011 10:28:09 GMT+0100 (CET)";
    creator = "System"; droits = ""; id = "8108e738-4f30-42e8-a9b5-32ab28afb185";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Mon Nov 26 2012 17:44:13 GMT+0100 (CET)"; modifier = "admin";
    miniature = ""; nodeType = "folder"; parentId = "3e4e9b05-f9f2-4443-823f-3fb9bf3e39a3";
    pathAlf = ""; size = 0; nomfichier = "Espaces Utilisateurs"; version = "";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = "Espaces Utilisateurs"};
    children = []};
   {author = ""; createPermission = true; created = "Tue Nov 08 2011 10:28:09 GMT+0100 (CET)";
    creator = "System"; droits = ""; id = "45929a9f-87ad-4438-8559-c787b2e51f47";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Tue Nov 08 2011 10:28:09 GMT+0100 (CET)"; modifier = "System";
    miniature = ""; nodeType = "folder"; parentId = "3e4e9b05-f9f2-4443-823f-3fb9bf3e39a3";
    pathAlf = ""; size = 0; nomfichier = "Espace invite"; version = "";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = "L'espace racine de l'Invite"};
    children = []};
   {author = ""; createPermission = true; created = "Fri Mar 23 2012 18:52:49 GMT+0100 (CET)";
    creator = "admin"; droits = ""; id = "76257b29-e6fb-4cff-ac8c-f676826c0e40";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Fri Mar 23 2012 18:52:49 GMT+0100 (CET)"; modifier = "admin";
    miniature = ""; nodeType = "folder"; parentId = "3e4e9b05-f9f2-4443-823f-3fb9bf3e39a3";
    pathAlf = ""; size = 0; nomfichier = "Partages"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Nov 21 2012 10:58:04 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "c6254dcf-d8bb-43ba-9139-7d19f44da1ba";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Nov 21 2012 10:58:05 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "8108e738-4f30-42e8-a9b5-32ab28afb185";
    pathAlf = ""; size = 0; nomfichier = "gdeponsay_MGRN"; version = "";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Nov 21 2012 11:03:41 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "32d372ce-a822-4f1f-a49c-173b0b17a73d";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Nov 21 2012 11:03:41 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "c6254dcf-d8bb-43ba-9139-7d19f44da1ba";
    pathAlf = ""; size = 0; nomfichier = "Dossier_cerfon"; version = "";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Nov 21 2012 11:21:47 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "03e0753d-0dc2-4d9f-bd03-5adfd9109b70";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Nov 21 2012 11:21:47 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "32d372ce-a822-4f1f-a49c-173b0b17a73d";
    pathAlf = ""; size = 0; nomfichier = "Sous_dossier_cerfon"; version = "";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Nov 21 2012 11:23:51 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "8b5a35e3-0153-453a-8b44-d685045f5448";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Nov 21 2012 11:23:51 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "c6254dcf-d8bb-43ba-9139-7d19f44da1ba";
    pathAlf = ""; size = 0; nomfichier = "Dossier_carnet"; version = "";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Nov 21 2012 11:26:28 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "a76bce10-67dc-4a2a-b2f4-00491b668ebd";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Nov 21 2012 11:26:28 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "c6254dcf-d8bb-43ba-9139-7d19f44da1ba";
    pathAlf = ""; size = 0; nomfichier = "Mantis"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Nov 21 2012 11:27:34 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "def43011-5362-4126-ab35-af1e7cb13d81";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Nov 21 2012 11:27:34 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "c6254dcf-d8bb-43ba-9139-7d19f44da1ba";
    pathAlf = ""; size = 0; nomfichier = "Clementine"; version = "";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Nov 21 2012 11:30:32 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "7dea199e-0ec9-4618-b8fd-f637219d7632";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Nov 21 2012 11:30:32 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "32d372ce-a822-4f1f-a49c-173b0b17a73d";
    pathAlf = ""; size = 0; nomfichier = "Perso"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Nov 21 2012 11:42:48 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "002e5d80-8582-4001-86b3-6b8c54f0fa36";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Nov 21 2012 11:42:48 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "32d372ce-a822-4f1f-a49c-173b0b17a73d";
    pathAlf = ""; size = 0; nomfichier = "Public"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Nov 21 2012 11:45:43 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "ef572a27-688b-4061-9328-13200541b5f3";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Nov 21 2012 11:45:43 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "32d372ce-a822-4f1f-a49c-173b0b17a73d";
    pathAlf = ""; size = 0; nomfichier = "Tank"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Nov 21 2012 18:24:06 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "c0ea3850-0de6-497a-a214-52307e2db04b";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Nov 21 2012 18:24:06 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "03e0753d-0dc2-4d9f-bd03-5adfd9109b70";
    pathAlf = ""; size = 0; nomfichier = "Dossier_particulier"; version = "";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Nov 21 2012 18:24:39 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "ba6046ac-dec0-4a7d-a7e6-6f4e4fdd7792";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Nov 21 2012 18:24:39 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "def43011-5362-4126-ab35-af1e7cb13d81";
    pathAlf = ""; size = 0; nomfichier = "Agrume"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Nov 21 2012 18:25:03 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "2bd13445-5f2a-49dc-9ddf-cd899efd8756";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Nov 21 2012 18:25:03 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "a76bce10-67dc-4a2a-b2f4-00491b668ebd";
    pathAlf = ""; size = 0; nomfichier = "Scell"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Nov 21 2012 18:27:44 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "47885523-b3dd-4b88-842c-f34dba1fcd5a";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Nov 21 2012 18:27:44 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "ba6046ac-dec0-4a7d-a7e6-6f4e4fdd7792";
    pathAlf = ""; size = 0; nomfichier = "Orange"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Nov 21 2012 18:27:59 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "519de8ce-07b7-4b07-a301-7a2fa55974d7";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Nov 21 2012 18:27:59 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "47885523-b3dd-4b88-842c-f34dba1fcd5a";
    pathAlf = ""; size = 0; nomfichier = "Rouge"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Nov 21 2012 18:28:10 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "6fdfd9e9-f87c-4a92-877d-3389cb8bbdeb";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Nov 21 2012 18:28:10 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "519de8ce-07b7-4b07-a301-7a2fa55974d7";
    pathAlf = ""; size = 0; nomfichier = "Vert"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Nov 21 2012 18:28:20 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "11b61c9c-829f-4f94-a5a4-2273c21b4c06";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Nov 21 2012 18:28:20 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "6fdfd9e9-f87c-4a92-877d-3389cb8bbdeb";
    pathAlf = ""; size = 0; nomfichier = "Bleu"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Nov 21 2012 18:29:20 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "8dff6c3c-fa2c-4ac6-aa67-c03cf239f7f1";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Nov 21 2012 18:29:20 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "8b5a35e3-0153-453a-8b44-d685045f5448";
    pathAlf = ""; size = 0; nomfichier = "Reunion kernel"; version = "";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Nov 21 2012 18:30:08 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "1ac6a6ac-dc35-4106-aa10-8553b281e860";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Nov 21 2012 18:30:08 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "8dff6c3c-fa2c-4ac6-aa67-c03cf239f7f1";
    pathAlf = ""; size = 0; nomfichier = "Ocaml"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Fri Nov 23 2012 16:09:09 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "a7a26657-519d-4673-a1bb-5fd127f5f7c1";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Fri Nov 23 2012 16:09:09 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "c6254dcf-d8bb-43ba-9139-7d19f44da1ba";
    pathAlf = ""; size = 0; nomfichier = "Chiffon"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Tue Nov 27 2012 14:23:07 GMT+0100 (CET)";
    creator = "Bruce_NHUr"; droits = ""; id = "86e88ca4-b3e8-41a2-a4e5-3a62c3e7da2e";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Tue Nov 27 2012 14:23:07 GMT+0100 (CET)"; modifier = "Bruce_NHUr";
    miniature = ""; nodeType = "folder"; parentId = "a76bce10-67dc-4a2a-b2f4-00491b668ebd";
    pathAlf = ""; size = 0; nomfichier = "Asticot"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Fri Nov 30 2012 11:30:10 GMT+0100 (CET)";
    creator = "Bruce_NHUr"; droits = ""; id = "45137f5b-0655-4b6b-befd-d9c3cab4fb1e";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Fri Nov 30 2012 11:30:10 GMT+0100 (CET)"; modifier = "Bruce_NHUr";
    miniature = ""; nodeType = "folder"; parentId = "a7a26657-519d-4673-a1bb-5fd127f5f7c1";
    pathAlf = ""; size = 0; nomfichier = "Doc"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Nov 21 2012 11:18:49 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "1b3a5b77-522c-46c3-be36-65d1242229c5";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Dec 12 2012 18:19:47 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "def43011-5362-4126-ab35-af1e7cb13d81";
    pathAlf = ""; size = 0; nomfichier = "Dossier_stage"; version = "";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Fri Nov 23 2012 14:52:17 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "da8da466-d5a1-46b2-8942-a22ab629e0ab";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Fri Nov 23 2012 14:52:17 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "1b3a5b77-522c-46c3-be36-65d1242229c5";
    pathAlf = ""; size = 0; nomfichier = "Materiaux"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Fri Nov 23 2012 14:54:29 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "fa504abc-8315-44f3-9a61-f812fbb515d5";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Fri Nov 23 2012 14:54:29 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "da8da466-d5a1-46b2-8942-a22ab629e0ab";
    pathAlf = ""; size = 0; nomfichier = "Bois"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Fri Nov 23 2012 16:20:25 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "51bfce96-608b-4c32-aa02-6ec665d7b008";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Fri Nov 23 2012 16:20:25 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "da8da466-d5a1-46b2-8942-a22ab629e0ab";
    pathAlf = ""; size = 0; nomfichier = "Briques"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Fri Nov 23 2012 14:51:58 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "9b02bdab-9482-4121-a975-871489031633";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Dec 12 2012 18:17:56 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "1b3a5b77-522c-46c3-be36-65d1242229c5";
    pathAlf = ""; size = 0; nomfichier = "Cheque"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Mon Nov 26 2012 10:40:28 GMT+0100 (CET)";
    creator = "gdeponsay_MGRN"; droits = ""; id = "0c7bc848-ba9b-4100-a33f-c1675bd3b49c";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Mon Nov 26 2012 10:40:28 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "folder"; parentId = "9b02bdab-9482-4121-a975-871489031633";
    pathAlf = ""; size = 0; nomfichier = "Cheque no1231564531"; version = "";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Dec 19 2012 17:10:43 GMT+0100 (CET)";
    creator = "Hulk_npRU"; droits = ""; id = "e8fd12ab-71f7-41f1-a987-06b4861ab4b8";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Dec 19 2012 17:10:43 GMT+0100 (CET)"; modifier = "Hulk_npRU";
    miniature = ""; nodeType = "folder"; parentId = "1b3a5b77-522c-46c3-be36-65d1242229c5";
    pathAlf = ""; size = 0; nomfichier = "Coucou"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Dec 19 2012 17:11:36 GMT+0100 (CET)";
    creator = "Hulk_npRU"; droits = ""; id = "12a1f3f4-9855-47da-86a5-b9da81109ddf";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Dec 19 2012 17:11:36 GMT+0100 (CET)"; modifier = "Hulk_npRU";
    miniature = ""; nodeType = "folder"; parentId = "1b3a5b77-522c-46c3-be36-65d1242229c5";
    pathAlf = ""; size = 0; nomfichier = "POlop"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Thu Dec 27 2012 15:18:22 GMT+0100 (CET)";
    creator = "Bruce_NHUr"; droits = ""; id = "0446419d-b6fe-456b-a7c8-36e33bbe081e";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Thu Dec 27 2012 15:18:22 GMT+0100 (CET)"; modifier = "Bruce_NHUr";
    miniature = ""; nodeType = "folder"; parentId = "c6254dcf-d8bb-43ba-9139-7d19f44da1ba";
    pathAlf = ""; size = 0; nomfichier = "Tirelipimpon"; version = "";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Thu Dec 27 2012 15:22:47 GMT+0100 (CET)";
    creator = "Bruce_NHUr"; droits = ""; id = "9df5934d-2184-4d5a-83da-d2cc9cbf6dc8";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Thu Dec 27 2012 15:22:47 GMT+0100 (CET)"; modifier = "Bruce_NHUr";
    miniature = ""; nodeType = "folder"; parentId = "c6254dcf-d8bb-43ba-9139-7d19f44da1ba";
    pathAlf = ""; size = 0; nomfichier = "le chat"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Thu Dec 27 2012 16:27:32 GMT+0100 (CET)";
    creator = "admin"; droits = ""; id = "3c52c914-9950-497d-9f28-643e529ea6b5";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Thu Dec 27 2012 16:27:32 GMT+0100 (CET)"; modifier = "admin";
    miniature = ""; nodeType = "folder"; parentId = "8108e738-4f30-42e8-a9b5-32ab28afb185";
    pathAlf = ""; size = 0; nomfichier = "FRANCE"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = "societe France"};
    children = []};
   {author = ""; createPermission = true; created = "Mon Jan 07 2013 12:02:26 GMT+0100 (CET)";
    creator = "admin"; droits = ""; id = "0a62d480-81bd-456d-a2cc-3a9360c150d2";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Mon Jan 07 2013 12:04:37 GMT+0100 (CET)"; modifier = "admin";
    miniature = ""; nodeType = "folder"; parentId = "3e4e9b05-f9f2-4443-823f-3fb9bf3e39a3";
    pathAlf = ""; size = 0; nomfichier = "myCowebo"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = "Ensemble des espaces myCowebo "};
    children = []};
   {author = ""; createPermission = true; created = "Mon Jan 07 2013 12:05:43 GMT+0100 (CET)";
    creator = "admin"; droits = ""; id = "4244b86e-cbca-443e-ac11-98e35a43a3a8";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Mon Jan 07 2013 12:05:43 GMT+0100 (CET)"; modifier = "admin";
    miniature = ""; nodeType = "folder"; parentId = "0a62d480-81bd-456d-a2cc-3a9360c150d2";
    pathAlf = ""; size = 0; nomfichier = "COWEBO"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = "Societe Cowebo"};
    children = []};
   {author = ""; createPermission = true; created = "Mon Jan 07 2013 12:03:10 GMT+0100 (CET)";
    creator = "admin"; droits = ""; id = "0102a23c-f535-48cf-9370-1e1460eb0078";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Mon Jan 07 2013 12:06:48 GMT+0100 (CET)"; modifier = "admin";
    miniature = ""; nodeType = "folder"; parentId = "0a62d480-81bd-456d-a2cc-3a9360c150d2";
    pathAlf = ""; size = 0; nomfichier = "PUBLIC"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre =
 {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = "Ensemble des espaces particuliers non rattaches à une Organisation "};
    children = []};
   {author = ""; createPermission = true; created = "Mon Jan 07 2013 12:12:20 GMT+0100 (CET)";
    creator = "admin"; droits = ""; id = "deff5e76-99ce-4d2b-b40c-993be01e811f";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Mon Jan 07 2013 12:12:20 GMT+0100 (CET)"; modifier = "admin";
    miniature = ""; nodeType = "folder"; parentId = "4244b86e-cbca-443e-ac11-98e35a43a3a8";
    pathAlf = ""; size = 0; nomfichier = "Espaces utilisateurs"; version = "";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = "Espaces utilisateurs Cowebo"};
    children = []};
   {author = ""; createPermission = true; created = "Mon Jan 07 2013 12:12:59 GMT+0100 (CET)";
    creator = "admin"; droits = ""; id = "cf8eba70-60f7-43a6-b34d-c49d810a453a";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Mon Jan 07 2013 12:12:59 GMT+0100 (CET)"; modifier = "admin";
    miniature = ""; nodeType = "folder"; parentId = "4244b86e-cbca-443e-ac11-98e35a43a3a8";
    pathAlf = ""; size = 0; nomfichier = "Espace Commun"; version = "";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Mon Jan 07 2013 12:19:02 GMT+0100 (CET)";
    creator = "admin"; droits = ""; id = "91e70d73-fec0-44a9-a77e-d9ae76840d32";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Mon Jan 07 2013 12:19:02 GMT+0100 (CET)"; modifier = "admin";
    miniature = ""; nodeType = "folder"; parentId = "deff5e76-99ce-4d2b-b40c-993be01e811f";
    pathAlf = ""; size = 0; nomfichier = "gdeponsay"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Mon Jan 07 2013 12:22:17 GMT+0100 (CET)";
    creator = "admin"; droits = ""; id = "1472c4a3-9e5f-4d03-9228-f8acabb16c87";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Mon Jan 07 2013 12:22:17 GMT+0100 (CET)"; modifier = "admin";
    miniature = ""; nodeType = "folder"; parentId = "deff5e76-99ce-4d2b-b40c-993be01e811f";
    pathAlf = ""; size = 0; nomfichier = "pavoye"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Jan 16 2013 15:03:03 GMT+0100 (CET)";
    creator = "qadam1_OwlB"; droits = ""; id = "18c547e7-c260-4fa7-99b5-03077c426343";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Jan 16 2013 15:03:03 GMT+0100 (CET)"; modifier = "qadam1_OwlB";
    miniature = ""; nodeType = "folder"; parentId = "c6254dcf-d8bb-43ba-9139-7d19f44da1ba";
    pathAlf = ""; size = 0; nomfichier = "alerte"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Jan 16 2013 15:03:41 GMT+0100 (CET)";
    creator = "qadam1_OwlB"; droits = ""; id = "cefcc226-87af-47db-b1aa-b3d96a3bedfd";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Jan 16 2013 15:03:41 GMT+0100 (CET)"; modifier = "qadam1_OwlB";
    miniature = ""; nodeType = "folder"; parentId = "c6254dcf-d8bb-43ba-9139-7d19f44da1ba";
    pathAlf = ""; size = 0; nomfichier = "alert"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Feb 06 2013 14:07:03 GMT+0100 (CET)";
    creator = "admin"; droits = ""; id = "eb68d5d2-88d9-4edb-b33a-a1c5616133c9";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Feb 06 2013 14:07:03 GMT+0100 (CET)"; modifier = "admin";
    miniature = ""; nodeType = "folder"; parentId = "8108e738-4f30-42e8-a9b5-32ab28afb185";
    pathAlf = ""; size = 0; nomfichier = "pavoye_gdp4_cowebo_com_QEKE";
    version = ""; versionable = true; messages_recus = []; messages_envoyes = [];
    infosDossier = []; cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Feb 06 2013 14:07:04 GMT+0100 (CET)";
    creator = "pavoye_gdp4_cowebo_com_QEKE"; droits = ""; id = "5b5eaab2-9893-4fb5-a23e-86ec89fd0af2";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Feb 06 2013 14:07:04 GMT+0100 (CET)"; modifier = "pavoye_gdp4_cowebo_com_QEKE";
    miniature = ""; nodeType = "folder"; parentId = "eb68d5d2-88d9-4edb-b33a-a1c5616133c9";
    pathAlf = ""; size = 0; nomfichier = "Partages"; version = ""; versionable = true;
    messages_recus = []; messages_envoyes = []; infosDossier = []; cercles = [];
    etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Feb 06 2013 14:07:04 GMT+0100 (CET)";
    creator = "pavoye_gdp4_cowebo_com_QEKE"; droits = ""; id = "2aa0cf19-172a-4156-85e4-7332e23f623d";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Feb 06 2013 14:07:04 GMT+0100 (CET)"; modifier = "pavoye_gdp4_cowebo_com_QEKE";
    miniature = ""; nodeType = "folder"; parentId = "eb68d5d2-88d9-4edb-b33a-a1c5616133c9";
    pathAlf = ""; size = 0; nomfichier = "PortefeuilleElectronique";
    version = ""; versionable = true; messages_recus = []; messages_envoyes = [];
    infosDossier = []; cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Feb 06 2013 14:42:14 GMT+0100 (CET)";
    creator = "pavoye_gdp4_cowebo_com_QEKE"; droits = ""; id = "1ff0aeff-ef1f-4948-8cb4-0097a3be94cc";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Feb 06 2013 14:42:14 GMT+0100 (CET)"; modifier = "pavoye_gdp4_cowebo_com_QEKE";
    miniature = ""; nodeType = "folder"; parentId = "5b5eaab2-9893-4fb5-a23e-86ec89fd0af2";
    pathAlf = ""; size = 0; nomfichier = "pavoye+mip4@cowebo.com"; version = "";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Feb 06 2013 16:06:26 GMT+0100 (CET)";
    creator = "pavoye_gdp4_cowebo_com_QEKE"; droits = ""; id = "cce0dff3-bb11-432d-bc07-3840308ba9db";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Feb 06 2013 16:06:27 GMT+0100 (CET)"; modifier = "pavoye_gdp4_cowebo_com_QEKE";
    miniature = ""; nodeType = "folder"; parentId = "eb68d5d2-88d9-4edb-b33a-a1c5616133c9";
    pathAlf = ""; size = 0; nomfichier = "Dossier_partage"; version = "";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = [];
    etatSignatureCoffre =
 {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne;
  empreinte_shaFichier =
   "eyJjbGFzc2lmX3RhZ3MiOlt7InR5cGVfY2xhc3NpZiI6IkRvc3NpZXIiLCJwdWJsaXF1ZSI6ZmFsc2UsInZhbGV1ciI6IkRvc3NpZXJfcGFydGFnw6kifV0sImV0YXRfY29mZnJlX2ZpY2hpZXIiOiJOb25Qcm90ZWdlIiwiZXRhdF9zaWduYXR1cmVfZmljaGllciI6Ik5vblNpZ25lIiwiZW1wcmVpbnRlX3NoYUZpY2hpZXIiOiIifQ=="};
    children = []};
   {author = ""; createPermission = true; created = "Wed Feb 06 2013 16:30:15 GMT+0100 (CET)";
    creator = "pavoye_gdp4_cowebo_com_QEKE"; droits = ""; id = "7fe650eb-ba6c-4955-8cb4-2319d7139ba0";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Feb 06 2013 16:30:17 GMT+0100 (CET)"; modifier = "pavoye_gdp4_cowebo_com_QEKE";
    miniature = ""; nodeType = "folder"; parentId = "eb68d5d2-88d9-4edb-b33a-a1c5616133c9";
    pathAlf = ""; size = 0; nomfichier = "Dossier auto test e à ç è ê ë ï";
    version = ""; versionable = true; messages_recus = []; messages_envoyes = [];
    infosDossier = []; cercles = [];
    etatSignatureCoffre =
 {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne;
  empreinte_shaFichier =
   "eyJjbGFzc2lmX3RhZ3MiOlt7InR5cGVfY2xhc3NpZiI6IkRvc3NpZXIiLCJwdWJsaXF1ZSI6ZmFsc2UsInZhbGV1ciI6IkRvc3NpZXIgYXV0byB0ZXN0IMOpIMOgIMOnIMOoIMOqIMOrIMOvIn1dLCJldGF0X2NvZmZyZV9maWNoaWVyIjoiTm9uUHJvdGVnZSIsImV0YXRfc2lnbmF0dXJlX2ZpY2hpZXIiOiJOb25TaWduZSIsImVtcHJlaW50ZV9zaGFGaWNoaWVyIjoiIn0="};
    children = []};
   {author = ""; createPermission = true; created = "Wed Feb 06 2013 16:33:51 GMT+0100 (CET)";
    creator = "pavoye_gdp4_cowebo_com_QEKE"; droits = ""; id = "18a7f87d-64a5-4c4b-8873-2ab9159c529a";
    isLink = false; linkTo = ""; isFolder = true; mimetype = "application/octet-stream";
    modified = "Wed Feb 06 2013 16:33:52 GMT+0100 (CET)"; modifier = "pavoye_gdp4_cowebo_com_QEKE";
    miniature = ""; nodeType = "folder"; parentId = "eb68d5d2-88d9-4edb-b33a-a1c5616133c9";
    pathAlf = ""; size = 0; nomfichier = "e è à ç âê î"; version = "";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = [];
    etatSignatureCoffre =
 {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne;
  empreinte_shaFichier =
   "eyJjbGFzc2lmX3RhZ3MiOlt7InR5cGVfY2xhc3NpZiI6IkRvc3NpZXIiLCJwdWJsaXF1ZSI6ZmFsc2UsInZhbGV1ciI6IsOpIMOoIMOgIMOnIMOiw6ogw64ifV0sImV0YXRfY29mZnJlX2ZpY2hpZXIiOiJOb25Qcm90ZWdlIiwiZXRhdF9zaWduYXR1cmVfZmljaGllciI6Ik5vblNpZ25lIiwiZW1wcmVpbnRlX3NoYUZpY2hpZXIiOiIifQ=="};
    children = []};
   {author = "Eric LE GAREC"; createPermission = true; created = "Thu Mar 15 2012 14:23:40 GMT+0100 (CET)";
    creator = "admin"; droits = ""; id = "f887e11c-ac72-4b1c-a2dc-cf36f81f5512";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Thu Mar 15 2012 14:23:43 GMT+0100 (CET)"; modifier = "admin";
    miniature = ""; nodeType = "document"; parentId = "8108e738-4f30-42e8-a9b5-32ab28afb185";
    pathAlf = ""; size = 2505224; nomfichier = "BX_Alfresco_Administration_1.pdf";
    version = "1.1"; versionable = true; messages_recus = []; messages_envoyes = [];
    infosDossier = []; cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = "Eric LE GAREC"; createPermission = true; created = "Thu Mar 15 2012 14:23:54 GMT+0100 (CET)";
    creator = "admin"; droits = ""; id = "3649dd0e-a0a6-410c-a118-d045bbdd52c8";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Thu Mar 15 2012 14:23:57 GMT+0100 (CET)"; modifier = "admin";
    miniature = ""; nodeType = "document"; parentId = "8108e738-4f30-42e8-a9b5-32ab28afb185";
    pathAlf = ""; size = 1275670; nomfichier = "BX_Alfresco_Extension_Configuration_1.pdf";
    version = "1.1"; versionable = true; messages_recus = []; messages_envoyes = [];
    infosDossier = []; cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = "Eric LE GAREC"; createPermission = true; created = "Thu Mar 15 2012 14:23:21 GMT+0100 (CET)";
    creator = "admin"; droits = ""; id = "9dda52c7-0c00-4668-b70b-66b3350d54c5";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Thu Mar 15 2012 14:23:25 GMT+0100 (CET)"; modifier = "admin";
    miniature = ""; nodeType = "document"; parentId = "8108e738-4f30-42e8-a9b5-32ab28afb185";
    pathAlf = ""; size = 6069080; nomfichier = "BX_Alfresco_Introduction_1.pdf";
    version = "1.1"; versionable = true; messages_recus = []; messages_envoyes = [];
    infosDossier = []; cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = "Eric LE GAREC"; createPermission = true; created = "Thu Mar 15 2012 14:24:13 GMT+0100 (CET)";
    creator = "admin"; droits = ""; id = "14d87da8-d4ca-48c1-9a6c-27028673d3e9";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Thu Mar 15 2012 14:24:16 GMT+0100 (CET)"; modifier = "admin";
    miniature = ""; nodeType = "document"; parentId = "8108e738-4f30-42e8-a9b5-32ab28afb185";
    pathAlf = ""; size = 1152306; nomfichier = "BX_Alfresco_Extension_Service_1.pdf";
    version = "1.1"; versionable = true; messages_recus = []; messages_envoyes = [];
    infosDossier = []; cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = "Jean Marie  PASCAL"; createPermission = true; created = "Fri Jan 06 2012 18:55:39 GMT+0100 (CET)";
    creator = "admin"; droits = ""; id = "858523a0-78fa-4ac6-9623-2e60ad9aea7b";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Thu Mar 29 2012 17:19:14 GMT+0200 (CEST)"; modifier = "admin";
    miniature = ""; nodeType = "document"; parentId = "45929a9f-87ad-4438-8559-c787b2e51f47";
    pathAlf = ""; size = 1888189; nomfichier = "alfrescosearchtutorial.pdf";
    version = "1.0"; versionable = true; messages_recus = []; messages_envoyes = [];
    infosDossier = []; cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = "Slide share presentation\r\n"};
    children = []};
   {author = "Guillaume de Ponsay"; createPermission = true; created = "Fri Nov 09 2012 17:50:08 GMT+0100 (CET)";
    creator = "admin"; droits = ""; id = "b862650c-8678-4176-8e81-2002d631eaf0";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Fri Nov 09 2012 17:50:10 GMT+0100 (CET)"; modifier = "admin";
    miniature = ""; nodeType = "document"; parentId = "45929a9f-87ad-4438-8559-c787b2e51f47";
    pathAlf = ""; size = 204390; nomfichier = "Mode\ycc\128le Factures.pdf";
    version = "1.0"; versionable = true; messages_recus = []; messages_envoyes = [];
    infosDossier = []; cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = "Alan F. Blackwell, Luke Church, Thomas Green"; createPermission = true;
    created = "Mon Nov 26 2012 18:33:42 GMT+0100 (CET)"; creator = "Bruce_NHUr";
    droits = ""; id = "ab419fb0-5391-43e4-94b8-8db2f64064f1"; isLink = false;
    linkTo = ""; isFolder = false; mimetype = "application/pdf"; modified = "Mon Nov 26 2012 18:33:43 GMT+0100 (CET)";
    modifier = "Bruce_NHUr"; miniature = ""; nodeType = "document"; parentId = "32d372ce-a822-4f1f-a49c-173b0b17a73d";
    pathAlf = ""; size = 67759; nomfichier = "test upl.pdf"; version = "1.0";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = "Alan F. Blackwell, Luke Church, Thomas Green"; createPermission = true;
    created = "Mon Nov 26 2012 19:01:40 GMT+0100 (CET)"; creator = "Bruce_NHUr";
    droits = ""; id = "ed44b004-623a-4fc0-8c0e-148b42289512"; isLink = false;
    linkTo = ""; isFolder = false; mimetype = "application/pdf"; modified = "Mon Nov 26 2012 19:01:40 GMT+0100 (CET)";
    modifier = "Bruce_NHUr"; miniature = ""; nodeType = "document"; parentId = "7dea199e-0ec9-4618-b8fd-f637219d7632";
    pathAlf = ""; size = 67759; nomfichier = "test upl 3.pdf"; version = "1.0";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Tue Nov 27 2012 11:00:22 GMT+0100 (CET)";
    creator = "Bruce_NHUr"; droits = ""; id = "22a09c40-a46b-40fe-b39b-fad1722f7d3c";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Wed Dec 12 2012 18:23:18 GMT+0100 (CET)"; modifier = "gdeponsay_MGRN";
    miniature = ""; nodeType = "document"; parentId = "11b61c9c-829f-4f94-a5a4-2273c21b4c06";
    pathAlf = ""; size = 31117; nomfichier = "Orange.pdf"; version = "1.0";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Tue Dec 18 2012 14:27:48 GMT+0100 (CET)";
    creator = "Hulk_npRU"; droits = ""; id = "9d6e9cb0-63ba-49e2-9959-6c8ffc542632";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Tue Dec 18 2012 14:27:48 GMT+0100 (CET)"; modifier = "Hulk_npRU";
    miniature = ""; nodeType = "document"; parentId = "c6254dcf-d8bb-43ba-9139-7d19f44da1ba";
    pathAlf = ""; size = 31117; nomfichier = "pdf.pdf"; version = "1.0";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Fri Dec 07 2012 11:13:08 GMT+0100 (CET)";
    creator = "Bruce_NHUr"; droits = ""; id = "e9655f91-6b43-4a93-a6e0-f0e3fba6db42";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Thu Dec 27 2012 11:04:58 GMT+0100 (CET)"; modifier = "Bruce_NHUr";
    miniature = ""; nodeType = "document"; parentId = "a76bce10-67dc-4a2a-b2f4-00491b668ebd";
    pathAlf = ""; size = 31117; nomfichier = "bugtracker"; version = "1.1";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Thu Dec 27 2012 16:07:17 GMT+0100 (CET)";
    creator = "Hulk_npRU"; droits = ""; id = "b3c20798-2d85-47c0-9243-ebfe0d7ea158";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Thu Dec 27 2012 16:07:18 GMT+0100 (CET)"; modifier = "Hulk_npRU";
    miniature = ""; nodeType = "document"; parentId = "9df5934d-2184-4d5a-83da-d2cc9cbf6dc8";
    pathAlf = ""; size = 1004635; nomfichier = "machine.pdf"; version = "1.0";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Fri Dec 28 2012 11:35:56 GMT+0100 (CET)";
    creator = "Bruce_NHUr"; droits = ""; id = "dfa1eaea-2c77-4f39-952c-7b0244b10aaa";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Fri Dec 28 2012 12:29:03 GMT+0100 (CET)"; modifier = "Bruce_NHUr";
    miniature = ""; nodeType = "document"; parentId = "9df5934d-2184-4d5a-83da-d2cc9cbf6dc8";
    pathAlf = ""; size = 1637145; nomfichier = "gdp.pdf"; version = "1.3";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Jan 02 2013 11:13:48 GMT+0100 (CET)";
    creator = "Bruce_NHUr"; droits = ""; id = "37f98c5b-b4bb-4a6f-8087-052a6730aea9";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Wed Jan 02 2013 11:13:50 GMT+0100 (CET)"; modifier = "Bruce_NHUr";
    miniature = ""; nodeType = "document"; parentId = "0446419d-b6fe-456b-a7c8-36e33bbe081e";
    pathAlf = ""; size = 1533909; nomfichier = "Sur le chiwawa.pdf";
    version = "1.0"; versionable = true; messages_recus = []; messages_envoyes = [];
    infosDossier = []; cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Jan 02 2013 11:15:20 GMT+0100 (CET)";
    creator = "Bruce_NHUr"; droits = ""; id = "e439506a-1191-4b26-9245-2a223424e802";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Wed Jan 02 2013 11:15:21 GMT+0100 (CET)"; modifier = "Bruce_NHUr";
    miniature = ""; nodeType = "document"; parentId = "0446419d-b6fe-456b-a7c8-36e33bbe081e";
    pathAlf = ""; size = 2743367; nomfichier = "avec la tete.pdf"; version = "1.0";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Jan 02 2013 11:25:22 GMT+0100 (CET)";
    creator = "inekein_tPKE"; droits = ""; id = "68213910-9fde-463c-9c54-9a64183ef94e";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Wed Jan 02 2013 11:25:22 GMT+0100 (CET)"; modifier = "inekein_tPKE";
    miniature = ""; nodeType = "document"; parentId = "c6254dcf-d8bb-43ba-9139-7d19f44da1ba";
    pathAlf = ""; size = 4325; nomfichier = "certif.pdf"; version = "1.0";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Jan 02 2013 15:01:14 GMT+0100 (CET)";
    creator = "inekein_tPKE"; droits = ""; id = "ab1d31bb-75f1-41e6-b1ed-d3a4c42e5349";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Wed Jan 02 2013 15:01:14 GMT+0100 (CET)"; modifier = "inekein_tPKE";
    miniature = ""; nodeType = "document"; parentId = "c6254dcf-d8bb-43ba-9139-7d19f44da1ba";
    pathAlf = ""; size = 4; nomfichier = "pass.pdf"; version = "1.0";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Jan 02 2013 15:31:04 GMT+0100 (CET)";
    creator = "inekein_tPKE"; droits = ""; id = "3f160e4c-d91b-49cc-8cb8-a1b393d53af5";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Wed Jan 02 2013 15:31:04 GMT+0100 (CET)"; modifier = "inekein_tPKE";
    miniature = ""; nodeType = "document"; parentId = "c6254dcf-d8bb-43ba-9139-7d19f44da1ba";
    pathAlf = ""; size = 4; nomfichier = "pass2.pdf"; version = "1.0";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Jan 02 2013 15:50:16 GMT+0100 (CET)";
    creator = "inekein_tPKE"; droits = ""; id = "aa4e9b85-ec48-4def-81f3-c044a451a991";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Wed Jan 02 2013 15:50:17 GMT+0100 (CET)"; modifier = "inekein_tPKE";
    miniature = ""; nodeType = "document"; parentId = "c6254dcf-d8bb-43ba-9139-7d19f44da1ba";
    pathAlf = ""; size = 4; nomfichier = "test.pdf"; version = "1.0";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Jan 02 2013 16:07:06 GMT+0100 (CET)";
    creator = "inekein_tPKE"; droits = ""; id = "e6b1e187-f481-4ae5-b4e3-34e755038740";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Wed Jan 02 2013 16:07:06 GMT+0100 (CET)"; modifier = "inekein_tPKE";
    miniature = ""; nodeType = "document"; parentId = "c6254dcf-d8bb-43ba-9139-7d19f44da1ba";
    pathAlf = ""; size = 45; nomfichier = "pass3.pdf"; version = "1.0";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Jan 02 2013 16:37:17 GMT+0100 (CET)";
    creator = "inekein_tPKE"; droits = ""; id = "6254ec88-6048-497d-b92c-fda6d057186b";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Wed Jan 02 2013 16:37:17 GMT+0100 (CET)"; modifier = "inekein_tPKE";
    miniature = ""; nodeType = "document"; parentId = "c6254dcf-d8bb-43ba-9139-7d19f44da1ba";
    pathAlf = ""; size = 173; nomfichier = "pass5.pdf"; version = "1.0";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Jan 02 2013 16:38:01 GMT+0100 (CET)";
    creator = "Bruce_NHUr"; droits = ""; id = "604d8fae-d5c6-4a10-b53d-6802cdd16f4a";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Wed Jan 02 2013 16:38:01 GMT+0100 (CET)"; modifier = "Bruce_NHUr";
    miniature = ""; nodeType = "document"; parentId = "0446419d-b6fe-456b-a7c8-36e33bbe081e";
    pathAlf = ""; size = 1546125; nomfichier = "un coup en haut.pdf";
    version = "1.0"; versionable = true; messages_recus = []; messages_envoyes = [];
    infosDossier = []; cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Jan 02 2013 16:39:54 GMT+0100 (CET)";
    creator = "Bruce_NHUr"; droits = ""; id = "4055d277-514b-4d34-a8dd-d4ca92ffe7b5";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Wed Jan 02 2013 16:39:56 GMT+0100 (CET)"; modifier = "Bruce_NHUr";
    miniature = ""; nodeType = "document"; parentId = "0446419d-b6fe-456b-a7c8-36e33bbe081e";
    pathAlf = ""; size = 2897072; nomfichier = "un coup en bas.pdf";
    version = "1.0"; versionable = true; messages_recus = []; messages_envoyes = [];
    infosDossier = []; cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Jan 02 2013 16:41:32 GMT+0100 (CET)";
    creator = "Bruce_NHUr"; droits = ""; id = "8f7b4eeb-57b9-470c-a553-87b61add5a5a";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Wed Jan 02 2013 16:41:33 GMT+0100 (CET)"; modifier = "Bruce_NHUr";
    miniature = ""; nodeType = "document"; parentId = "0446419d-b6fe-456b-a7c8-36e33bbe081e";
    pathAlf = ""; size = 1823358; nomfichier = "tatoumi.pdf"; version = "1.0";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = "Scott Loganbill"; createPermission = true; created = "Mon Jan 07 2013 11:30:05 GMT+0100 (CET)";
    creator = "qadam1_OwlB"; droits = ""; id = "944b1f48-1ac9-4e02-8099-8685d07c50eb";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Mon Jan 07 2013 11:30:05 GMT+0100 (CET)"; modifier = "qadam1_OwlB";
    miniature = ""; nodeType = "document"; parentId = "c6254dcf-d8bb-43ba-9139-7d19f44da1ba";
    pathAlf = ""; size = 268860; nomfichier = "Lundi 7.pdf"; version = "1.0";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Thu Jan 10 2013 11:25:42 GMT+0100 (CET)";
    creator = "inekein_tPKE"; droits = ""; id = "fb52d041-36d9-4488-b4bf-6cc11072c318";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Thu Jan 10 2013 11:25:42 GMT+0100 (CET)"; modifier = "inekein_tPKE";
    miniature = ""; nodeType = "document"; parentId = "9df5934d-2184-4d5a-83da-d2cc9cbf6dc8";
    pathAlf = ""; size = 5878922; nomfichier = "test avec chargement.pdf";
    version = "1.0"; versionable = true; messages_recus = []; messages_envoyes = [];
    infosDossier = []; cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = ""; createPermission = true; created = "Wed Feb 06 2013 14:07:05 GMT+0100 (CET)";
    creator = "pavoye_gdp4_cowebo_com_QEKE"; droits = ""; id = "4d4b4168-b745-49d9-b3be-f8d0e91fc09b";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/octet-stream";
    modified = "Wed Feb 06 2013 14:46:53 GMT+0100 (CET)"; modifier = "pavoye_gdp4_cowebo_com_QEKE";
    miniature = ""; nodeType = "document"; parentId = "2aa0cf19-172a-4156-85e4-7332e23f623d";
    pathAlf = ""; size = 108; nomfichier = "Portefeuille_data.json";
    version = "1.2"; versionable = true; messages_recus = []; messages_envoyes = [];
    infosDossier = []; cercles = []; etatSignatureCoffre = {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne; empreinte_shaFichier = ""};
    children = []};
   {author = "Alan F. Blackwell, Luke Church, Thomas Green"; createPermission = true;
    created = "Wed Feb 06 2013 14:38:46 GMT+0100 (CET)"; creator = "pavoye_mip4_cowebo_com_BWB0";
    droits = ""; id = "a852e88f-56d4-4eaf-812f-8a21af3c93a1"; isLink = false;
    linkTo = ""; isFolder = false; mimetype = "application/octet-stream";
    modified = "Wed Feb 06 2013 14:49:50 GMT+0100 (CET)"; modifier = "pavoye_gdp4_cowebo_com_QEKE";
    miniature = ""; nodeType = "document"; parentId = "24599d72-b9c5-418e-aa45-f93c94ae2685";
    pathAlf = ""; size = 104238; nomfichier = "20th-blackwell.pdf"; version = "2.5";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = [];
    etatSignatureCoffre =
 {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne;
  empreinte_shaFichier =
   "eyJjbGFzc2lmX3RhZ3MiOlt7InR5cGVfY2xhc3NpZiI6IkRvc3NpZXIiLCJwdWJsaXF1ZSI6dHJ1ZSwidmFsZXVyIjoiTGVzIERvY3VtZW50cyBQYXJ0YWfDqXMgYXZlYyBtb2kifSx7InR5cGVfY2xhc3NpZiI6IkRvc3NpZXIiLCJwdWJsaXF1ZSI6dHJ1ZSwidmFsZXVyIjoiLyJ9XSwiZXRhdF9jb2ZmcmVfZmljaGllciI6WyJQcm90ZWdlX2xlX3BhciIsW1sxMzYwMTU4NTkwLjEzNDU1NywicGF2b3llK2dkcDRAY293ZWJvLmNvbSJdLFsxMzYwMTU4NTg4LjA0NDMyNywicGF2b3llK21pcDRAY293ZWJvLmNvbSJdLFsxMzYwMTU3OTY3LjM4NzgxOCwicGF2b3llK21pcDRAY293ZWJvLmNvbSJdLFsxMzYwMTU3OTM0LjgxNDI2LCJwYXZveWUrbWlwNEBjb3dlYm8uY29tIl1dXSwiZXRhdF9zaWduYXR1cmVfZmljaGllciI6WyJTaWduZSIsW1sxMzYwMTU4NTgzLjc4MzE0NywicGF2b3llK2dkcDRAY293ZWJvLmNvbSJdLFsxMzYwMTU3OTYzLjQ5MDI1MywicGF2b3llK21pcDRAY293ZWJvLmNvbSJdXV0sImVtcHJlaW50ZV9zaGFGaWNoaWVyIjoiNmVkOGMzYmE3YTQ0NzhmMTFmYTBmMTViZGFiZTIwNTM0NTAwYzQ0YSJ9"};
    children = []};
   {author = "Alan F. Blackwell, Luke Church, Thomas Green"; createPermission = true;
    created = "Wed Feb 06 2013 16:07:57 GMT+0100 (CET)"; creator = "pavoye_gdp4_cowebo_com_QEKE";
    droits = ""; id = "dc537ac1-6d13-4478-b9a8-a1d78de3c0ae"; isLink = false;
    linkTo = ""; isFolder = false; mimetype = "application/pdf"; modified = "Wed Feb 06 2013 16:08:04 GMT+0100 (CET)";
    modifier = "pavoye_gdp4_cowebo_com_QEKE"; miniature = ""; nodeType = "document";
    parentId = "cce0dff3-bb11-432d-bc07-3840308ba9db"; pathAlf = "";
    size = 67758; nomfichier = "20th-blackwell.pdf"; version = "1.2";
    versionable = true; messages_recus = []; messages_envoyes = []; infosDossier = [];
    cercles = [];
    etatSignatureCoffre =
 {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne;
  empreinte_shaFichier =
   "eyJjbGFzc2lmX3RhZ3MiOlt7InR5cGVfY2xhc3NpZiI6IkRvc3NpZXIiLCJwdWJsaXF1ZSI6dHJ1ZSwidmFsZXVyIjoiRG9zc2llcl9wYXJ0YWdlIn0seyJ0eXBlX2NsYXNzaWYiOiJEb3NzaWVyIiwicHVibGlxdWUiOnRydWUsInZhbGV1ciI6IkRvc3NpZXJfcGFydGFnw6kifV0sImV0YXRfY29mZnJlX2ZpY2hpZXIiOiJOb25Qcm90ZWdlIiwiZXRhdF9zaWduYXR1cmVfZmljaGllciI6Ik5vblNpZ25lIiwiZW1wcmVpbnRlX3NoYUZpY2hpZXIiOiI2ZWQ4YzNiYTdhNDQ3OGYxMWZhMGYxNWJkYWJlMjA1MzQ1MDBjNDRhIn0="};
    children = []};
   {author = ""; createPermission = true; created = "Wed Feb 06 2013 16:10:53 GMT+0100 (CET)";
    creator = "pavoye_mip4_cowebo_com_BWB0"; droits = ""; id = "856e0e6d-d02e-4296-95fe-70a681ed85a0";
    isLink = false; linkTo = ""; isFolder = false; mimetype = "application/pdf";
    modified = "Wed Feb 06 2013 16:18:26 GMT+0100 (CET)"; modifier = "pavoye_mip4_cowebo_com_BWB0";
    miniature = ""; nodeType = "document"; parentId = "7d4f4182-f23c-4a0b-a210-034a066171c6";
    pathAlf = ""; size = 68943; nomfichier = "TEMPORAL LOGIC FOR MAN.pdf";
    version = "1.3"; versionable = true; messages_recus = []; messages_envoyes = [];
    infosDossier = []; cercles = [];
    etatSignatureCoffre =
 {classif_tags = []; etat_coffre_fichier = NonProtege; etat_signature_fichier = NonSigne;
  empreinte_shaFichier =
   "eyJjbGFzc2lmX3RhZ3MiOlt7InR5cGVfY2xhc3NpZiI6IkRvc3NpZXIiLCJwdWJsaXF1ZSI6dHJ1ZSwidmFsZXVyIjoiTGVzIERvY3VtZW50cyBQYXJ0YWfDqXMgYXZlYyBtb2kifSx7InR5cGVfY2xhc3NpZiI6IkRvc3NpZXIiLCJwdWJsaXF1ZSI6dHJ1ZSwidmFsZXVyIjoiRG9zc2llcl9wYXJ0YWdlIn0seyJ0eXBlX2NsYXNzaWYiOiJEb3NzaWVyIiwicHVibGlxdWUiOnRydWUsInZhbGV1ciI6IkRvc3NpZXJfcGFydGFnw6kifV0sImV0YXRfY29mZnJlX2ZpY2hpZXIiOiJOb25Qcm90ZWdlIiwiZXRhdF9zaWduYXR1cmVfZmljaGllciI6Ik5vblNpZ25lIiwiZW1wcmVpbnRlX3NoYUZpY2hpZXIiOiIxYWRjNmMzZjFjZjNlMzFlM2JkMzgyOThjMzI4MzE5NmIxZGU0MTAzIn0="};
   children = []}];;



let h = Hashtbl.create 1024;;

Hashtbl.add h "856e0e6d-d02e-4296-95fe-70a681ed85a0" (List.hd arbo);;


List.iter (fun n -> Hashtbl.add h n.id n) arbo;;

(*
try Hashtbl.find h "fa504abc-8315-44f3-9a61-f812fbb515d5" with e -> print_string "pas trouvé"; failwith "pas trouvé";;
*)

(*
Hashtbl.remove h "fa504abc-8315-44f3-9a61-f812fbb515d5";;
*)

(*
try Hashtbl.find h "fa504abc-8315-44f3-9a61-f812fbb515d5" with e -> print_string "pas trouvé"; failwith "pas trouvé";;
*)

let to_list h =  Hashtbl.fold (fun k v acc -> (k, v) :: acc) h [];;

(* to_arbo : ArborescenceCowebo_t.itemFS list -> ArborescenceCowebo_t.itemFS list*)

 (*http://ocaml-extlib.googlecode.com/svn/doc/apiref/ExtHashtbl.Hashtbl.html*)

let arborify arbolist =

        let trouve_et_enleve h cle =
                let   _  = print_endline ("ENTREEE      "^(string_of_int((ExtHashtbl.Hashtbl.length h)))) in
                let elem = Hashtbl.find_all h cle in
                let _    = ExtHashtbl.Hashtbl.remove_all h cle in
                let _    = print_endline ("Sortie    "^(string_of_int((ExtHashtbl.Hashtbl.length h)))) in
                elem in

        let hpid = Hashtbl.create 1024 in
        let _   = List.iter (fun n -> Hashtbl.add hpid n.parentId n) arbolist in

        let hid = Hashtbl.create 1024 in
        let _   = List.iter (fun n -> Hashtbl.add hid n.id n) arbo in

        let racines = List.filter (fun n -> not (Hashtbl.mem hid n.parentId) && n.isFolder ) arbolist in
        let _       = List.iter   (fun n -> ExtHashtbl.Hashtbl.remove_all hpid n.parentId) racines in
        let rec construit_arbre node =
                match ExtHashtbl.Hashtbl.length hpid > 0 with
                | true  -> print_endline (string_of_int((ExtHashtbl.Hashtbl.length hpid )));
                           print_endline node.id;
                                 { node with children = List.map construit_arbre (trouve_et_enleve hpid node.id)}
                | false ->  node 
        in

        (List.map construit_arbre racines), hpid, hid, racines;;

